### ISSUE TITLE
More Cpp questions

### ISSUE THREAD

**Issue by sagarkattel** [Vyom-Yadav/Cpp#1]
## Hello @Vyom-Yadav 
Your Cpp repo is amazing but it is not being continued and it has less Content

**I can Contribute to it** 
**Can i Contribute to it?**

What i Can add?
- [x] Leetcode Answers
- [x] Atleast one or more approach to solve the given Problem

**Comment by Vyom-Yadav** [comment]
These are just notes on the basic concepts of CPP, I have not included any questions in these, not sure if this is the best place to add leetcode questions as they are as related to algorithms rather than the concepts of the language. Thanks for asking though :).
